title: <p align="center">Shah Yousuf Quadri</p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/yousuf-quadri-99625426//">LinkedIn</a> |
  <a href="https://github.com/YousufQuadri">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Worked with Synechron Tech as Senior Software Engineer.
  Working in finance domain for 7 years.
  <br>
  </p>



theme: jekyll-theme-minimal
